# Global settings - most REQUIRED
time_framework = [2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050]
foresight = 5   # Has to be a multiple of the minimum separation between the years in time framework
regions = ["UK"]
interest_rate = 0.1
interpolation_mode = 'Active'
log_level = 'info'

# Convergence parameters
equilibrium_variable = 'demand'
maximum_iterations = 100
tolerance = 0.1
tolerance_unmet_demand = -0.1

[[outputs]]
quantity = "prices"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[[outputs]]
quantity = "capacity"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"
index = false
keep_columns = ['technology', 'dst_region', 'region', 'installed', 'agent', 'sector', 'type', 'year', 'capacity']

[[outputs]]
quantity = "consumption"
sink = "aggregate"
filename = "{path}/{default_output_dir}/MCA{Quantity}.csv"
#columns = ["commodity",	"region",	"installed",	"technology", "year",	"agent",	"category",	"sector",	"consumption"]

# Carbon budget control
[carbon_budget_control]
budget = []

[global_input_files]
projections = '{path}/Projections.csv'
global_commodities = '{path}/GlobalCommodities.csv'


[sectors.building]
type = 'default'
priority = 1
dispatch_production = 'share'

technodata = '{path}/Technodata.csv'
technodata_timeslices = '{path}/TechnodataTimeslices.csv'
commodities_in = '{path}/CommIn.csv'
commodities_out = '{path}/CommOut.csv'

[sectors.building.subsectors.retro_and_new]
agents = '{path}/Agents.csv'



existing_capacity = '{path}/ExistingCapacity.csv'

lpsolver = "adhoc" # Optional, defaults to "scipy" or "adhoc"

constraints = [  # Optional, defaults to the constraints below
    "max_production",
    "max_capacity_expansion",
    "demand",
    "search_space",
]
demand_share = "standard_demand"   #"standard_demand"  # Optional, default to new_and_retro
forecast = 5  # Optional, defaults to 5 



[[sectors.building.outputs]]
filename = '{cwd}/{default_output_dir}/{Sector}/{Quantity}/{year}{suffix}'
quantity = "capacity"
sink = 'csv'
overwrite = true
index = false

#[[sectors.building.interactions]] 
#net = 'new_to_retro'
#interaction = 'transfer'


[sectors.building_presets]
type = 'presets'
priority = 0
consumption_path= "{path}/Consumption*.csv"

[timeslices]
W.Night = 638.75
W.Day = 912.5
W.Peak = 273.75  # was calld ".Evening_peak"
W.Evening = 365.0 # was called ".Late_evening"
P.Night = 638.75
P.Day = 912.5
P.Peak = 273.75
P.Evening = 365.0
S.Night = 638.75
S.Day = 912.5
S.Peak = 273.75
S.Evening = 365.0
A.Night = 638.75
A.Day = 912.5
A.Peak = 273.75
A.Evening = 365.0
level_names = ['season','period']